### ISSUE TITLE
Finish CDS/CDNSKEY implementation

### ISSUE THREAD

**Issue by vlevigneron** [zonemaster/zonemaster-ldns#114]
- Specific methods for CDS/CDNSKEY ressource records need to be implemented.

**Comment by pnax** [comment]
Since the CDS (resp CDNSKEY) resource record format [is identical to the DS record](https://www.rfc-editor.org/rfc/rfc7344#section-3.1) (resp [DNSKEY record](https://www.rfc-editor.org/rfc/rfc7344#section-3.2)), we could make the Zonemaster::LDNS::RR::CDS (resp Zonemaster::LDNS::RR::CDNSKEY) a subclass of Zonemaster::LDNS::RR::DS (resp Zonemaster::LDNS::RR::DNSKEY).
