### ISSUE TITLE
macOS no longer supported?

### ISSUE THREAD

**Issue by cdybedahl** [zonemaster/zonemaster-ldns#96]
Commit fbc6808af431de2e2ae826055e3dfda5a5c76ede removes the ability to build the module on macOS. If this wasn't intentional, please fix. If it was intentional, please document.

**Comment by matsduf** [comment]
The commit belongs to PR #44 which is documented in issue #43. It was not intentional to remove support for MacOS, but the parameters were not documented and MacOS is not one of the OSs that the project officially support so we have not seen the issue.

If you can provide a PR of needed changes to make it work under MacOS including documentation of use and purpose we should be able to included it given that those changes are compatible with the OSs that we do support.

**Comment by matsduf** [comment]
@cdybedahl, any comment on your side?

**Comment by matsduf** [comment]
@cdybedahl, do you have more information or can we close this issue?

**Comment by matsduf** [comment]
We welcome a pull request to resolve this issue, but we cannot fix it within the team. We close this issue.

**Comment by matsduf** [comment]
Zonemaster-CLI is now supported on Docker, and it works on both MacOS and Windows.
